### ISSUE TITLE
pytorch=1.9.1, pyg==2.0.3, PackagesNotFoundError

### ISSUE THREAD

**Issue by Greay83** [chao1224/MoleculeSTM#3]
Hi, this is a very cool work, thanks for sharing this repository.
When I followed the following command to install the pytorch and pyg package, I encountered the following problem.

command:
conda install -y -c conda-forge -c pytorch pytorch=1.9.1
conda install -y -c pyg -c conda-forge pyg==2.0.3

problem:
PackagesNotFoundError: The following packages are not available from current channels:

Then I use the search bar at the top of the web page('https://anaconda.org'), but the required version package was not found on the page.

I would like to know if you have encountered the same problem and how did you solve it.
Thank you in advance :)

**Comment by chao1224** [comment]
Hi @Greay83,

Thank you for your interest!

I guess this can be caused by the different versions of conda. We explicitly put this for reproducibility, and there could be three ways to handle this:
1. I started this project around May 2022, so you can downgrade your miniconda/anaconda to that timepoint.
2. I do not have access to NVIDIA machines now, but I can get this environment using anaconda-2019.10.
3. I guess you can also use the latest version of pytorch and pyg.

Hope these help.

**Comment by Greay83** [comment]
Thank you for your notice!
I would like to try it.
Sincerely.

**Comment by Greay83** [comment]
Sorry to bother you again. 
When trying various solutions, I guess this issues can be caused by the different versions of cuda. Could you please provide some details on the cuda version of your running environment?
Thank you in advance :)

**Comment by chao1224** [comment]
Hi @Greay83, I tried the following, which works on my current machine:
```
>>> print(torch.version.cuda)
10.2
```

**Comment by Greay83** [comment]
Thank you for your notice!
Sincerely.
